server:
  port: 8081


# log4j2 配置
logging:
  config: classpath:log4j2-spring.xml

# spring 配置
spring:
  # 数据格式
  jackson:
    date-format: yyyy-mm-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10GB

  # thymeleaf 缓存配置
  thymeleaf:
    cache: false

  # bean 注入
  main:
    allow-bean-definition-overriding: true

  # 数据库配置
  datasource:
    username: MPCDSEPC
    password: bCHzbS2DTxxXm8Ni
    url: jdbc:mysql://xayytech.com:3306/mpcdsepc
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 162.14.110.70
    port: 6379
    password: lhz20021215
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    mapper-locations: classpath*:**/xml/*.xml
