server:
  port: 8081

# mybatis 配置
mybatis:
  type-aliases-package: com.yytech.mpcdsepc.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    use-generated-keys: true

# log4j2 配置
logging:
  config: classpath:log4j2-spring.xml

# spring 配置
spring:
  # 数据格式
  jackson:
    date-format: yyyy-mm-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

  # thymeleaf 缓存配置
  thymeleaf:
    cache: false

  # bean 注入
  main:
    allow-bean-definition-overriding: true

  # 数据库配置
  datasource:
    username: MPCDSEPC
    password: bCHzbS2DTxxXm8Ni
    url: jdbc:mysql://xayytech.com:3306/mpcdsepc
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ncld.nwu.edu.cn
    port: 6379
    database: 1 #请勿修改
    password: 20020602mM
